### ISSUE TITLE
Create Project structure

### ISSUE THREAD

**Issue by AdronTech** [WARRExploration/Rover_II#17]
define the project and repository structure

**Comment by AdronTech** [comment]
I thought we are creating a repository for each package. I do not think it is possible to clone multiple repositories in one place. Because those packages would have to be directly in the catkin workspace. Or is there another way to nest them in subfolders?

**Comment by vstarlinger** [comment]
The structure will be 

- catkin_ws
     - src
          - repo1
          - repo2
          - repo3
          - repo4
          - repo5

thats totally fine

**Comment by AdronTech** [comment]
You are probably right.
https://answers.ros.org/question/119581/catkin-structure/
